[package]
name = "alen"
version = "0.2.0"
authors = ["Jakob Nybo Nissen <jakobnybonissen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.37"
bio = "0.34.0"
clap = "2.33.3"
crossterm = "0.20.0"
regex = "1.4.2"
unicode-segmentation = "1.7.1"
