cargo-features = ["strip"]

[package]
name = "alen"
version = "0.2.0"
authors = ["Jakob Nybo Nissen <jakobnybonissen@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
description = "A command-like program to view DNA or protein alignments in FASTA formats."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.37"
bio = "0.34.0"
crossterm = "0.20.0"
gumdrop = "0.8.0"
regex = "1.4.2"
unicode-segmentation = "1.7.1"

[profile.release]
strip = "symbols"
opt-level = 'z'
lto = true
