name: Build and Test

on:
  pull_request: {}
  push:
    branches: [ master ]

jobs:
  matrix-build:
    name: Build
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        toolchain: [stable]
        experimental: [false]
        include:
          - {toolchain: stable, os: windows-latest, experimental: false, flags: ""}
          - {toolchain: stable, os: macos-latest, experimental: false, flags: ""}
          - {toolchain: beta, os: ubuntu-latest, experimental: false, flags: ""}
          - {toolchain: nightly, os: ubuntu-latest, experimental: true, flags: ""}
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{matrix.toolchain}}
        override: true
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
  linux-static:
    name: Static Build (Linux x86_64)
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Toolchain
      uses: actions-rs/toolchain@v1
      with:
        target: x86_64-unknown-linux-musl
        toolchain: stable
        override: true
    - name: Install Musl
      run: sudo apt install -f musl-dev
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --target x86_64-unknown-linux-musl
  rustfmt:
    name: Formatting and Style
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy
    - name: Run Rustfmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
    - name: Run Clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -Dclippy::all
